### ISSUE TITLE
:me doesn't work for mastodon

### ISSUE THREAD

**Issue by er-vin** [edas/TweetDeletion#7]
I got a bunch of rules including "by(:me)" in their construct. They work as expected for Twitter, but they're never hit for Mastodon. Likewise for rules containing fav_by(:me) or rt_by(:me).

I'm not sure how to debug that or get you more information. Guidance welcome.

**Comment by edas** [comment]
Hi

Thank you for your report.

Do you have a minimal exemple of configuration that doesn't work as expected ? if possible a toot that does not validate your config ?

**Comment by er-vin** [comment]
I wish... I noticed because some of them are gone which I didn't expect to go away. But one of the rules in question is:
keep_if (by(:me) and contains("sketch")), tag:" S "

And it still delete toots I posted containing that word. On the mastodon side it's gone for good, but the equivalent example on the Twitter side (I cross-post all) is:
https://twitter.com/dr_ervin/status/1091696558742138881

**Comment by er-vin** [comment]
And indeed something is weird, if I do the poor man debugging, that is adding "print(account_name)" at the entrance of the accounts loop, I indeed see "ervin@mamot.fr", now if I add "print(tweet.account_name)" in the for_tweets loop I get "acct@" which looks wrong.

**Comment by er-vin** [comment]
Probably can be closed now that #8 went in.

**Comment by edas** [comment]
Thank you for your help
